name: Phoenix Inwarranty Flow collection execution

on: 
  push: 
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  run-postman-tests:
    runs-on: myec2linux
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install nodejs and npm
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '22'
          
      - name: Install newman and html-extra globally
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra
          
      - name: Run the postman collection with newman
        continue-on-error: true
        run: |
          mkdir -p newman
          newman run 'Inwarranty-flow_Collection.postman_collection.json' \
            -e QA.postman_environment.json \
            -d testData.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export ./newman/index.html
             
      - name: Upload a newman report
        if: always()
        uses: actions/upload-artifact@v7.0.0
        with:
          name: Newman Report
          path: newman/*.html

      - name: Creating github page branch
        if: always()
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
          publish_branch: gh-pages
          force_orphan: true
      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }} #NOT GMAIL PASSWORD!!! USE APP PASSWORD
          subject: 🚀 API Test Report - GitHub Actions
          to: danielnepoleon6994@gmail.com
          from: Jatin from GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello,
            Please find the attached HTML report generated after running the Postman tests via GitHub Actions.
            Link to live report (GitHub Pages): https://jatin99.github.io/Phoenix-Inwarranty-Flow/
            Regards,
            GitHub Actions 🤖
        
          attachments: newman/index.html
          

  
